server:
  port: 8060

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: 1805
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888

